mode = "dark"

accent = "#aca1cf"
selection = "#3b3b3e"
muted = "#757581"

background = "#161617"
dark_background = "#131314"
darker_background = "#0e0e0f"
lighter_background = "#27272a"

foreground = "#c9c7cd"
dark_foreground = "#757581"
light_foreground = "#c1c0d4"
bright_foreground = "#d3d1d7"

red = "#ea83a5"
yellow = "#e6b99d"
orange = "#ebb097"
green = "#90b99f"
cyan = "#85b5ba"
blue = "#92a2d5"
magenta = "#aca1cf"
brown = "#6b5a58"

bright_red = "#ed96b3"
bright_yellow = "#eac5ae"
bright_green = "#a7c8b3"
bright_cyan = "#97c0c4"
bright_blue = "#acb1d7"
bright_magenta = "#b7aed5"
